import 'food_search_models.dart';

class KenyanFoodCatalogEntry {
  final FoodSearchResult result;
  final List<String> aliases;

  const KenyanFoodCatalogEntry({
    required this.result,
    required this.aliases,
  });
}

class KenyanFoodCatalog {
  KenyanFoodCatalog._();

  static final List<KenyanFoodCatalogEntry> entries = [
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15053',
        name: 'Githeri (Stewed Maize & Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 157,
        carbsPer100g: 19.7,
        proteinPer100g: 6.7,
        fatPer100g: 4.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri', 'stewed maize and beans', 'maize and beans', 'maharagwe na mahindi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15055',
        name: 'Githeri (Sauteed Fresh Maize & Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 185,
        carbsPer100g: 17.8,
        proteinPer100g: 6.9,
        fatPer100g: 7.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri fresh maize', 'sauteed fresh maize and beans', 'fresh maize and beans'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15060',
        name: 'Githeri (Fresh Beans & Maize)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 180,
        carbsPer100g: 15.1,
        proteinPer100g: 7.8,
        fatPer100g: 7.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri fresh beans', 'fresh beans and maize', 'green beans and maize'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15054',
        name: 'Mukimo (Maize, Beans, Potatoes & Pumpkin Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 118,
        carbsPer100g: 20.5,
        proteinPer100g: 5.0,
        fatPer100g: 0.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo', 'irio', 'maize beans potatoes pumpkin leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15057',
        name: 'Mukimo (Fresh Maize, Potatoes & Pumpkin Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 109,
        carbsPer100g: 18.5,
        proteinPer100g: 3.0,
        fatPer100g: 1.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo fresh maize', 'irio fresh maize', 'fresh maize potatoes pumpkin leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15059',
        name: 'Mukimo wa Njahi (Black Beans, Green Bananas & Potatoes)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 164,
        carbsPer100g: 26.5,
        proteinPer100g: 9.5,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo wa njahi', 'njahi mukimo', 'black beans green bananas potatoes'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15062',
        name: 'Mukimo wa Njahi (Raw & Ripe Bananas)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 151,
        carbsPer100g: 26.6,
        proteinPer100g: 6.4,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo wa njahi bananas', 'njahi bananas', 'raw ripe bananas njahi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15056',
        name: 'Matoke (Stewed Green Bananas & Meat)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 118,
        carbsPer100g: 13.3,
        proteinPer100g: 6.0,
        fatPer100g: 4.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['matoke', 'matooke', 'stewed green bananas and meat', 'green banana stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15086',
        name: 'Muthokoi (Dehulled Maize and Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 161,
        carbsPer100g: 19.8,
        proteinPer100g: 5.0,
        fatPer100g: 5.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['muthokoi', 'dehulled maize and beans', 'shelled maize and beans'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15017',
        name: 'Omena Stew (Silver Sardine Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 180,
        carbsPer100g: 6.0,
        proteinPer100g: 8.8,
        fatPer100g: 13.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['omena', 'omena stew', 'silver sardine stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15087',
        name: 'Beef Stew',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 181,
        carbsPer100g: 3.8,
        proteinPer100g: 17.7,
        fatPer100g: 10.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['beef stew', 'nyama stew', 'mchuzi wa nyama'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15066-rice',
        name: 'Biryani Rice',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 152,
        carbsPer100g: 27.9,
        proteinPer100g: 2.7,
        fatPer100g: 3.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['biryani rice', 'wali wa biryani'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15066-stew',
        name: 'Biryani Stew (Swahili Spiced Beef Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 198,
        carbsPer100g: 8.3,
        proteinPer100g: 8.1,
        fatPer100g: 14.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['biryani stew', 'swahili spiced beef stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15074',
        name: 'Wali wa Kuchemshwa (Boiled Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 138,
        carbsPer100g: 27.2,
        proteinPer100g: 2.7,
        fatPer100g: 2.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wali wa kuchemshwa', 'boiled rice', 'plain rice'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15075',
        name: 'Wali wa Yasmin (Onion Fried Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 185,
        carbsPer100g: 31.2,
        proteinPer100g: 3.2,
        fatPer100g: 5.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wali wa yasmin', 'onion fried rice'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15081',
        name: 'Chai ya Maziwa (Mixed Tea)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 36,
        carbsPer100g: 5.4,
        proteinPer100g: 1.1,
        fatPer100g: 1.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['chai ya maziwa', 'milk tea', 'kenyan tea', 'chai'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15005',
        name: 'Whole Maize Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 141,
        carbsPer100g: 26.0,
        proteinPer100g: 3.3,
        fatPer100g: 1.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['ugali', 'maize ugali', 'whole maize ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15009',
        name: 'Refined Maize Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 148,
        carbsPer100g: 27.3,
        proteinPer100g: 3.4,
        fatPer100g: 1.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['refined maize ugali', 'sifted ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15100',
        name: 'Finger Millet Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 120,
        carbsPer100g: 21.0,
        proteinPer100g: 2.9,
        fatPer100g: 0.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['finger millet ugali', 'wimbi ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15051',
        name: 'Ugali (Cassava, Fingermillet and Sorghum Flour)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 145,
        carbsPer100g: 30.7,
        proteinPer100g: 2.0,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['cassava finger millet sorghum ugali', 'mixed flour ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15019',
        name: 'White Chapati',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 424,
        carbsPer100g: 49.6,
        proteinPer100g: 7.8,
        fatPer100g: 21.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['chapati', 'white chapati', 'chapo'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15020',
        name: 'Brown Chapati',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 413,
        carbsPer100g: 40.9,
        proteinPer100g: 7.3,
        fatPer100g: 22.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['brown chapati', 'whole wheat chapati'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15001',
        name: 'Uji wa Mahindi (Maize Porridge)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 52,
        carbsPer100g: 8.5,
        proteinPer100g: 1.5,
        fatPer100g: 1.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji', 'uji wa mahindi', 'maize porridge', 'porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15014',
        name: 'Finger Millet Porridge (Uji wa Wimbi)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 40,
        carbsPer100g: 7.8,
        proteinPer100g: 0.7,
        fatPer100g: 0.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa wimbi', 'finger millet porridge', 'wimbi porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15002',
        name: 'Sorghum, Finger Millet and Maize Porridge',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 41,
        carbsPer100g: 6.3,
        proteinPer100g: 1.3,
        fatPer100g: 0.9,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['sorghum finger millet maize porridge', 'mixed grain porridge', 'uji wa mtama wimbi na mahindi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15003',
        name: 'Kaimati (Fried Dumplings)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 429,
        carbsPer100g: 52.8,
        proteinPer100g: 4.6,
        fatPer100g: 21.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kaimati', 'fried dumplings', 'swahili dumplings'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15004',
        name: 'Mahamri (Swahili Doughnuts)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 413,
        carbsPer100g: 46.6,
        proteinPer100g: 6.0,
        fatPer100g: 22.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mahamri', 'swahili doughnuts', 'mandazi ya mahamri'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15006',
        name: 'Maize and Finger Millet Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 133,
        carbsPer100g: 24.0,
        proteinPer100g: 3.1,
        fatPer100g: 1.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['maize and finger millet ugali', 'mahindi na wimbi ugali', 'mixed maize millet ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15007',
        name: 'Maize, Red Sorghum and Finger Millet Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 129,
        carbsPer100g: 23.3,
        proteinPer100g: 3.1,
        fatPer100g: 1.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['maize red sorghum finger millet ugali', 'mahindi mtama mwekundu na wimbi ugali', 'three grain ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15008',
        name: 'Cassava and Red Sorghum Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 116,
        carbsPer100g: 23.4,
        proteinPer100g: 2.1,
        fatPer100g: 0.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['cassava and red sorghum ugali', 'muhogo na mtama mwekundu ugali', 'cassava sorghum ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15010',
        name: 'Sorghum, Maize Flour and Finger Millet Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 150,
        carbsPer100g: 32.1,
        proteinPer100g: 1.9,
        fatPer100g: 0.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['sorghum maize flour finger millet ugali', 'mtama mahindi na wimbi ugali', 'mixed flour ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15011',
        name: 'Cassava Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 186,
        carbsPer100g: 43.7,
        proteinPer100g: 1.1,
        fatPer100g: 0.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['cassava flour ugali', 'muhogo ugali', 'ugali wa muhogo'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15012',
        name: 'Cassava, Millet and Sorghum Porridge',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 46,
        carbsPer100g: 10.2,
        proteinPer100g: 0.5,
        fatPer100g: 0.1,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['cassava millet sorghum porridge', 'uji wa muhogo mawele na mtama', 'mixed root grain porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15013',
        name: 'Cassava Porridge (Uji wa Muhogo)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 28,
        carbsPer100g: 6.8,
        proteinPer100g: 0.1,
        fatPer100g: 0.0,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa muhogo', 'cassava porridge', 'muhogo porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15015',
        name: 'Bulrush Millet Porridge (Uji wa Mawele)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 83,
        carbsPer100g: 15.7,
        proteinPer100g: 2.0,
        fatPer100g: 1.0,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa mawele', 'bulrush millet porridge', 'mawele porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15016',
        name: 'Rice Flour Porridge (Uji wa Mchele)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 56,
        carbsPer100g: 10.2,
        proteinPer100g: 0.6,
        fatPer100g: 1.3,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa mchele', 'rice flour porridge', 'rice porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15018',
        name: 'Busara (Whole Maize and Finger Millet Porridge)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 40,
        carbsPer100g: 7.3,
        proteinPer100g: 1.0,
        fatPer100g: 0.3,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['busara', 'whole maize and finger millet porridge', 'mahindi na wimbi porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15022',
        name: 'Fried Egg (Mayai ya Kukaangwa)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 223,
        carbsPer100g: 2.5,
        proteinPer100g: 13.1,
        fatPer100g: 17.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['fried egg', 'mayai ya kukaangwa', 'egg fried'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15023',
        name: 'Omelette',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 121,
        carbsPer100g: 5.3,
        proteinPer100g: 6.6,
        fatPer100g: 7.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['omelette', 'omelet', 'mayai ya kukunjwa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15024',
        name: 'Spanish Omelette',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 161,
        carbsPer100g: 3.2,
        proteinPer100g: 7.5,
        fatPer100g: 12.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['spanish omelette', 'spanish omelet', 'omelette ya viazi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15025',
        name: 'Meat Samosa (Sambusa ya Nyama)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 443,
        carbsPer100g: 40.5,
        proteinPer100g: 18.8,
        fatPer100g: 22.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['meat samosa', 'sambusa ya nyama', 'beef samosa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15026',
        name: 'Vegetable Samosa (Sambusa ya Mboga)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 325,
        carbsPer100g: 40.2,
        proteinPer100g: 8.5,
        fatPer100g: 13.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['vegetable samosa', 'sambusa ya mboga', 'veggie samosa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15027',
        name: 'Pancakes (Chapati za Maji)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 270,
        carbsPer100g: 39.2,
        proteinPer100g: 8.3,
        fatPer100g: 8.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pancakes', 'chapati za maji', 'kenyan pancakes'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15028',
        name: 'Tosti Mayai (Egg Toast)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 280,
        carbsPer100g: 32.4,
        proteinPer100g: 12.5,
        fatPer100g: 10.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['tosti mayai', 'egg toast', 'mayai toast'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15029',
        name: 'Drop Scones',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 449,
        carbsPer100g: 37.4,
        proteinPer100g: 7.1,
        fatPer100g: 29.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['drop scones', 'scones', 'kenyan drop scones'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15030',
        name: 'Terere (Stir-fried Amaranth Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 83,
        carbsPer100g: 2.9,
        proteinPer100g: 3.0,
        fatPer100g: 5.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['terere', 'stir fried amaranth leaves', 'amaranth leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15031',
        name: 'Sukumawiki (Stir-fried Kales)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 54,
        carbsPer100g: 2.1,
        proteinPer100g: 2.5,
        fatPer100g: 3.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['sukumawiki', 'sukuma wiki', 'stir fried kales', 'kales'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15032',
        name: 'Stir-fried Cabbage',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 100,
        carbsPer100g: 3.1,
        proteinPer100g: 1.2,
        fatPer100g: 8.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stir fried cabbage', 'fried cabbage', 'cabbage'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15033',
        name: 'Mrenda & Seveve (Jute Mallow & Pumpkin Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 59,
        carbsPer100g: 5.4,
        proteinPer100g: 3.4,
        fatPer100g: 2.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mrenda and seveve', 'mrenda', 'seveve', 'jute mallow and pumpkin leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15034',
        name: 'Pumpkin Leaves',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 99,
        carbsPer100g: 5.5,
        proteinPer100g: 3.2,
        fatPer100g: 6.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pumpkin leaves', 'majani ya malenge', 'malenge leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15035',
        name: 'Saget, Terere & Managu (Spider Plant, Amaranth & African Nightshade Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 60,
        carbsPer100g: 4.5,
        proteinPer100g: 4.3,
        fatPer100g: 1.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['saget terere and managu', 'saget', 'terere and managu', 'mixed indigenous vegetables'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15036',
        name: 'Pilau (Spiced Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 213,
        carbsPer100g: 24.8,
        proteinPer100g: 6.9,
        fatPer100g: 9.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pilau', 'spiced rice', 'pilau rice'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15037',
        name: 'Mseto wa Ndengu (Rice with Green Grams)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 103,
        carbsPer100g: 18.4,
        proteinPer100g: 3.7,
        fatPer100g: 1.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mseto wa ndengu', 'rice with green grams', 'wali na ndengu'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15038',
        name: 'Mseto wa Maharagwe (Rice with Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 193,
        carbsPer100g: 23.5,
        proteinPer100g: 5.0,
        fatPer100g: 7.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mseto wa maharagwe', 'rice with beans', 'wali na maharagwe'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15039',
        name: 'Nderema (Vine Spinach)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 72,
        carbsPer100g: 1.4,
        proteinPer100g: 3.2,
        fatPer100g: 5.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['nderema', 'vine spinach', 'malabar spinach'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15040',
        name: 'Fiqe (Red Sorghum, Beans and Teff Flour)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 192,
        carbsPer100g: 24.2,
        proteinPer100g: 7.2,
        fatPer100g: 5.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['fiqe', 'red sorghum beans and teff flour', 'sorghum bean teff mix'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15041',
        name: 'Qanchibelo (Beef, Maize & Wheat Flour)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 133,
        carbsPer100g: 15.7,
        proteinPer100g: 9.6,
        fatPer100g: 3.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['qanchibelo', 'beef maize and wheat flour', 'maize wheat beef mix'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15042',
        name: 'Qita (Maize and Wheat Flour Pancake)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 241,
        carbsPer100g: 41.2,
        proteinPer100g: 5.1,
        fatPer100g: 5.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['qita', 'maize and wheat flour pancake', 'maize wheat pancake'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15043',
        name: 'Gurdo, Marqa (Ugali in Sour Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 242,
        carbsPer100g: 29.7,
        proteinPer100g: 6.6,
        fatPer100g: 9.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['gurdo marqa', 'ugali in sour milk', 'marqa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15044',
        name: 'Mchuzi wa Ndengu (Green Gram Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 109,
        carbsPer100g: 9.3,
        proteinPer100g: 6.3,
        fatPer100g: 4.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mchuzi wa ndengu', 'green gram stew', 'ndengu stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15045',
        name: 'Mchuzi wa Maharagwe (Bean Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 63,
        carbsPer100g: 7.2,
        proteinPer100g: 3.5,
        fatPer100g: 1.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mchuzi wa maharagwe', 'bean stew', 'maharagwe stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15046',
        name: 'Mchuzi wa Ndengu Kamande (Lentil Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 108,
        carbsPer100g: 11.1,
        proteinPer100g: 7.1,
        fatPer100g: 3.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mchuzi wa ndengu kamande', 'lentil stew', 'kamande stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15047',
        name: 'Nyirinyiri (Camel Meat)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 521,
        carbsPer100g: 20.0,
        proteinPer100g: 34.6,
        fatPer100g: 33.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['nyirinyiri', 'camel meat', 'fried camel meat'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15048',
        name: 'Mbuboyi (Blood Cooked in Fresh Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 97,
        carbsPer100g: 8.3,
        proteinPer100g: 11.5,
        fatPer100g: 2.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mbuboyi', 'blood cooked in fresh milk', 'blood and milk dish'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15049',
        name: 'Ashir',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 125,
        carbsPer100g: 25.8,
        proteinPer100g: 2.7,
        fatPer100g: 0.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['ashir', 'cereal porridge mix', 'somali ashir'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15052',
        name: 'Yam Stew',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 94,
        carbsPer100g: 15.3,
        proteinPer100g: 1.5,
        fatPer100g: 2.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['yam stew', 'stewed yam', 'viazi vikuu stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15058',
        name: 'Stewed Potatoes & Arrowroots',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 90,
        carbsPer100g: 15.0,
        proteinPer100g: 1.9,
        fatPer100g: 2.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed potatoes and arrowroots', 'potatoes and arrowroots', 'viazi na nduma'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15061',
        name: 'Mashed Potato and Bananas',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 179,
        carbsPer100g: 22.1,
        proteinPer100g: 2.3,
        fatPer100g: 8.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mashed potato and bananas', 'potato and banana mash', 'viazi na ndizi mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15063',
        name: 'Groundnut Sauce',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 298,
        carbsPer100g: 9.6,
        proteinPer100g: 10.6,
        fatPer100g: 23.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['groundnut sauce', 'peanut sauce', 'mchuzi wa karanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15064',
        name: 'Vimumunya vya Chumvi (Pumpkin & Coconut Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 72,
        carbsPer100g: 4.6,
        proteinPer100g: 1.3,
        fatPer100g: 4.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['vimumunya vya chumvi', 'pumpkin and coconut milk', 'savory pumpkin coconut'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15065',
        name: 'Vinolo (Banana and Maize Flour Ugali)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 124,
        carbsPer100g: 25.5,
        proteinPer100g: 2.2,
        fatPer100g: 0.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['vinolo', 'banana and maize flour ugali', 'ndizi na unga wa mahindi ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15067',
        name: 'Vimumunya vya Sukari (Sweetened Pumpkin & Coconut Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 93,
        carbsPer100g: 14.5,
        proteinPer100g: 1.1,
        fatPer100g: 3.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['vimumunya vya sukari', 'sweetened pumpkin and coconut milk', 'sweet pumpkin coconut'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15068',
        name: 'Wukunu (Sweet Potatoes & Dehulled Black Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 94,
        carbsPer100g: 15.8,
        proteinPer100g: 4.1,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wukunu', 'sweet potatoes and dehulled black beans', 'sweet potato black bean mix'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15069',
        name: 'Mushenye (Green Maize and Sweet Potatoes)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 153,
        carbsPer100g: 17.6,
        proteinPer100g: 7.1,
        fatPer100g: 4.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mushenye', 'green maize and sweet potatoes', 'mahindi mabichi na viazi vitamu'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15070',
        name: 'Ingokho (Stewed Chicken)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 211,
        carbsPer100g: 6.4,
        proteinPer100g: 18.3,
        fatPer100g: 12.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['ingokho', 'stewed chicken', 'chicken stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15071',
        name: 'Malesele (Cow Blood with Sour Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 335,
        carbsPer100g: 15.4,
        proteinPer100g: 20.0,
        fatPer100g: 21.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['malesele', 'cow blood with sour milk', 'blood and sour milk'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15072',
        name: 'Tsiswa (Stewed Termites)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 515,
        carbsPer100g: 7.3,
        proteinPer100g: 31.6,
        fatPer100g: 38.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['tsiswa', 'stewed termites', 'termites stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15073',
        name: 'Ingokho (Fried Chicken)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 532,
        carbsPer100g: 9.1,
        proteinPer100g: 44.6,
        fatPer100g: 35.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['fried chicken', 'ingokho fried', 'kuku ya kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15076',
        name: 'Stir-fried Spinach',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 74,
        carbsPer100g: 2.0,
        proteinPer100g: 2.8,
        fatPer100g: 5.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stir fried spinach', 'fried spinach', 'spinach'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15077',
        name: 'Thabai / Thaa (Stinging Nettle Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 34,
        carbsPer100g: 1.9,
        proteinPer100g: 1.2,
        fatPer100g: 2.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['thabai', 'thaa', 'stinging nettle leaves', 'nettle leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15078',
        name: 'Rhikhuvi (Stewed Cowpea Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 152,
        carbsPer100g: 3.5,
        proteinPer100g: 3.2,
        fatPer100g: 13.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['rhikhuvi', 'stewed cowpea leaves', 'kunde leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15079',
        name: 'Kunde and Mrenda (Stewed Cowpeas and Jute Mallow Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 57,
        carbsPer100g: 4.4,
        proteinPer100g: 3.7,
        fatPer100g: 2.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kunde and mrenda', 'stewed cowpeas and jute mallow leaves', 'kunde mrenda'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15080',
        name: 'Obwoba (Stewed Mushrooms in Peanut Butter)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 117,
        carbsPer100g: 8.3,
        proteinPer100g: 4.9,
        fatPer100g: 6.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['obwoba', 'stewed mushrooms in peanut butter', 'mushrooms in peanut sauce'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15082',
        name: 'Stewed Dried Fish',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 330,
        carbsPer100g: 3.9,
        proteinPer100g: 25.7,
        fatPer100g: 23.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed dried fish', 'dried fish stew', 'samaki wa kukaushwa stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15083',
        name: 'Kimanga cha Ndizi (Smoked Green Bananas and Kidney Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 146,
        carbsPer100g: 24.1,
        proteinPer100g: 6.5,
        fatPer100g: 0.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kimanga cha ndizi', 'smoked green bananas and kidney beans', 'ndizi na kidney beans'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15084',
        name: 'Kimanga cha Mihogo (Mashed Cassava and Pigeon Peas)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 194,
        carbsPer100g: 39.6,
        proteinPer100g: 4.8,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kimanga cha mihogo', 'mashed cassava and pigeon peas', 'mihogo na mbaazi mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15085',
        name: 'Ndoto (Sauteed Red Kidney Beans & Red Sorghum)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 193,
        carbsPer100g: 21.3,
        proteinPer100g: 5.7,
        fatPer100g: 7.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['ndoto', 'sauteed red kidney beans and red sorghum', 'kidney beans and sorghum'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15088',
        name: 'Munono (Cow Blood, Beef, Cow Fat)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 549,
        carbsPer100g: 4.6,
        proteinPer100g: 19.5,
        fatPer100g: 50.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['munono', 'cow blood beef cow fat', 'blood beef fat mix'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15089',
        name: 'Osarge Ogkole (Fresh Blood and Fresh Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 81,
        carbsPer100g: 7.0,
        proteinPer100g: 6.1,
        fatPer100g: 3.1,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['osarge ogkole', 'fresh blood and fresh milk', 'blood and fresh milk'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15090',
        name: 'Kimanga cha Viazi Vitamu (Mashed Sweet Potato & Black Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 112,
        carbsPer100g: 18.9,
        proteinPer100g: 5.4,
        fatPer100g: 0.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kimanga cha viazi vitamu', 'mashed sweet potato and black beans', 'viazi vitamu na beans mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15091',
        name: 'Kitojo (Sweet Potato Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 144,
        carbsPer100g: 1.4,
        proteinPer100g: 3.9,
        fatPer100g: 12.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kitojo', 'sweet potato leaves', 'majani ya viazi vitamu'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15092',
        name: 'Mchuzi wa Mbaazi (Pigeon Peas Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 118,
        carbsPer100g: 11.0,
        proteinPer100g: 5.7,
        fatPer100g: 4.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mchuzi wa mbaazi', 'pigeon peas stew', 'mbaazi stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15093',
        name: 'Nchenga / Nzenga (Crushed Maize)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 129,
        carbsPer100g: 20.3,
        proteinPer100g: 2.2,
        fatPer100g: 3.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['nchenga', 'nzenga', 'crushed maize'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15094',
        name: 'Mseto wa Viazi (Potatoes in Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 111,
        carbsPer100g: 21.1,
        proteinPer100g: 2.2,
        fatPer100g: 1.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mseto wa viazi', 'potatoes in rice', 'wali na viazi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15095',
        name: 'Likhanga (Stewed Guinea Fowl)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 154,
        carbsPer100g: 2.0,
        proteinPer100g: 15.8,
        fatPer100g: 9.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['likhanga', 'stewed guinea fowl', 'guinea fowl stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15096',
        name: 'Fried Tilapia',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 437,
        carbsPer100g: 0.3,
        proteinPer100g: 45.7,
        fatPer100g: 28.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['fried tilapia', 'tilapia', 'tilapia ya kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15097',
        name: 'Stewed Green Bananas',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 84,
        carbsPer100g: 10.4,
        proteinPer100g: 1.0,
        fatPer100g: 3.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed green bananas', 'green bananas', 'ndizi mbichi stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15098',
        name: 'Stir Fried Beef',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 255,
        carbsPer100g: 5.0,
        proteinPer100g: 26.7,
        fatPer100g: 14.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stir fried beef', 'fried beef', 'nyama ya kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15099',
        name: 'Stir Fried Goat Meat',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 383,
        carbsPer100g: 10.4,
        proteinPer100g: 32.1,
        fatPer100g: 23.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stir fried goat meat', 'fried goat meat', 'mbuzi ya kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15101',
        name: 'Omena wa Kukaangwa (Fried Omena)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 450,
        carbsPer100g: 4.6,
        proteinPer100g: 19.2,
        fatPer100g: 39.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['omena wa kukaangwa', 'fried omena', 'omena fried'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15102',
        name: 'Aluru (Stewed Quails)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 195,
        carbsPer100g: 5.2,
        proteinPer100g: 11.3,
        fatPer100g: 14.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['aluru', 'stewed quails', 'quail stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15103',
        name: 'Mashed Potatoes',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 106,
        carbsPer100g: 22.8,
        proteinPer100g: 2.5,
        fatPer100g: 0.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mashed potatoes', 'potato mash', 'viazi mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15104',
        name: 'Mashed Bananas',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 81,
        carbsPer100g: 16.9,
        proteinPer100g: 1.2,
        fatPer100g: 0.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mashed bananas', 'banana mash', 'ndizi mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15105',
        name: 'Enriched Mashed Potatoes',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 141,
        carbsPer100g: 18.6,
        proteinPer100g: 2.0,
        fatPer100g: 6.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['enriched mashed potatoes', 'fortified mashed potatoes', 'rich potato mash'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15106',
        name: 'Enriched Mashed Bananas',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 136,
        carbsPer100g: 14.3,
        proteinPer100g: 1.0,
        fatPer100g: 7.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['enriched mashed bananas', 'fortified mashed bananas', 'rich banana mash'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15107',
        name: 'Stewed Nile Perch',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 125,
        carbsPer100g: 2.5,
        proteinPer100g: 14.3,
        fatPer100g: 6.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed nile perch', 'nile perch stew', 'sangara stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15108',
        name: 'Stewed Goat Meat',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 222,
        carbsPer100g: 5.2,
        proteinPer100g: 17.1,
        fatPer100g: 14.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed goat meat', 'goat meat stew', 'mbuzi stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15109',
        name: 'Pan Fried Sweet Potatoes',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 248,
        carbsPer100g: 25.3,
        proteinPer100g: 3.1,
        fatPer100g: 13.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pan fried sweet potatoes', 'fried sweet potatoes', 'viazi vitamu vya kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15110',
        name: 'Potato Chips',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 326,
        carbsPer100g: 44.4,
        proteinPer100g: 4.8,
        fatPer100g: 13.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['potato chips', 'chips', 'fries'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15111',
        name: 'Kimito (Mashed Beans & Potatoes)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 127,
        carbsPer100g: 21.6,
        proteinPer100g: 5.7,
        fatPer100g: 0.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['kimito', 'mashed beans and potatoes', 'beans and potatoes mash'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15112',
        name: 'Arrowroot Stew',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 91,
        carbsPer100g: 14.9,
        proteinPer100g: 1.9,
        fatPer100g: 2.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['arrowroot stew', 'nduma stew', 'stewed arrowroot'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15113',
        name: 'Sweet Potatoes with Peanut Butter',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 89,
        carbsPer100g: 9.3,
        proteinPer100g: 2.2,
        fatPer100g: 4.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['sweet potatoes with peanut butter', 'viazi vitamu na peanut butter', 'sweet potatoes in peanut butter'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15114',
        name: 'Black Bean Stew (Dolichos / Njahi Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 62,
        carbsPer100g: 7.7,
        proteinPer100g: 3.6,
        fatPer100g: 1.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['black bean stew', 'njahi stew', 'dolichos stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15115',
        name: 'Bean Stew with Milk and Cream',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 139,
        carbsPer100g: 14.3,
        proteinPer100g: 7.2,
        fatPer100g: 4.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['bean stew with milk and cream', 'creamy bean stew', 'maharagwe na maziwa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15116',
        name: 'Mcheleng (Rice with Milk)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 176,
        carbsPer100g: 27.2,
        proteinPer100g: 3.9,
        fatPer100g: 5.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mcheleng', 'rice with milk', 'wali na maziwa'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15117',
        name: 'Pan Fried Arrowroots',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 181,
        carbsPer100g: 28.3,
        proteinPer100g: 4.1,
        fatPer100g: 5.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pan fried arrowroots', 'fried arrowroots', 'nduma za kukaanga'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15118',
        name: 'Nyenyi (Mashed Pigeon Peas & Green Maize)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 125,
        carbsPer100g: 17.8,
        proteinPer100g: 4.9,
        fatPer100g: 2.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['nyenyi', 'mashed pigeon peas and green maize', 'mbaazi na mahindi mabichi mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15119',
        name: 'Finger Millet and Sorghum Porridge',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 74,
        carbsPer100g: 9.7,
        proteinPer100g: 2.7,
        fatPer100g: 2.2,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['finger millet and sorghum porridge', 'wimbi na mtama porridge', 'mixed millet sorghum porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15120',
        name: 'Mashed Pumpkin and Black Nightshade Leaves',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 67,
        carbsPer100g: 4.9,
        proteinPer100g: 3.8,
        fatPer100g: 2.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mashed pumpkin and black nightshade leaves', 'pumpkin and managu mash', 'malenge na managu mashed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15121',
        name: 'Enriched Matoke',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 111,
        carbsPer100g: 15.8,
        proteinPer100g: 2.4,
        fatPer100g: 3.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['enriched matoke', 'fortified matoke', 'matoke enriched'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15122',
        name: 'Oatmeal',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 83,
        carbsPer100g: 12.9,
        proteinPer100g: 2.4,
        fatPer100g: 1.7,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['oatmeal', 'oats porridge', 'oats'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15123',
        name: 'Uji wa Shayiri (Oat Porridge)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 86,
        carbsPer100g: 15.3,
        proteinPer100g: 1.9,
        fatPer100g: 1.6,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa shayiri', 'oat porridge', 'shayiri porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15124',
        name: 'Enriched Mandazi (East African Doughnuts; Enriched)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 379,
        carbsPer100g: 49.9,
        proteinPer100g: 7.6,
        fatPer100g: 16.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['enriched mandazi', 'fortified mandazi', 'mandazi enriched'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15125',
        name: 'Basic Mandazi (East African Doughnuts; Basic)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 340,
        carbsPer100g: 48.7,
        proteinPer100g: 6.4,
        fatPer100g: 12.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['basic mandazi', 'mandazi', 'east african doughnuts'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15126',
        name: 'Stewed Split Dal',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 69,
        carbsPer100g: 8.1,
        proteinPer100g: 3.7,
        fatPer100g: 1.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['stewed split dal', 'dal stew', 'split dal'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15127',
        name: 'Potato Curry',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 145,
        carbsPer100g: 17.3,
        proteinPer100g: 2.2,
        fatPer100g: 7.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['potato curry', 'viazi curry', 'curried potatoes'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15128',
        name: 'Peas and Brinjal Curry',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 131,
        carbsPer100g: 6.6,
        proteinPer100g: 4.2,
        fatPer100g: 8.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['peas and brinjal curry', 'eggplant and peas curry', 'brinjal curry'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15129',
        name: 'Wali wa Mvuke (Steamed Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 121,
        carbsPer100g: 26.7,
        proteinPer100g: 2.6,
        fatPer100g: 0.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wali wa mvuke', 'steamed rice', 'rice steamed'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15130',
        name: 'Roti (Indian Chapati)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 374,
        carbsPer100g: 43.8,
        proteinPer100g: 8.0,
        fatPer100g: 16.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['roti', 'indian chapati', 'chapati ya kihindi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15131',
        name: 'Potato Bhajia',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 471,
        carbsPer100g: 37.1,
        proteinPer100g: 8.6,
        fatPer100g: 31.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['potato bhajia', 'bhajia', 'viazi bhajia'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15132',
        name: 'Chaas (Diluted Yoghurt)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 60,
        carbsPer100g: 8.0,
        proteinPer100g: 2.0,
        fatPer100g: 2.2,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['chaas', 'diluted yoghurt', 'buttermilk'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15133',
        name: 'Siro (Semolina & Nuts)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 412,
        carbsPer100g: 39.4,
        proteinPer100g: 4.3,
        fatPer100g: 26.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['siro', 'semolina and nuts', 'semolina nut porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15134',
        name: 'Minced Meat Balls',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 157,
        carbsPer100g: 18.6,
        proteinPer100g: 8.1,
        fatPer100g: 5.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['minced meat balls', 'meat balls', 'nyama balls'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15136',
        name: 'Uji wa Ngano (Wheat Flour Porridge)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 111,
        carbsPer100g: 16.1,
        proteinPer100g: 2.5,
        fatPer100g: 3.9,
        defaultQuantity: 100,
        quantityUnit: 'ml',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa ngano', 'wheat flour porridge', 'ngano porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15137',
        name: 'Okra Meat Dish',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 94,
        carbsPer100g: 3.2,
        proteinPer100g: 8.2,
        fatPer100g: 5.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['okra meat dish', 'okra with meat', 'bamia na nyama'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15138',
        name: 'Hydrabadi Biryani',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 195,
        carbsPer100g: 21.4,
        proteinPer100g: 8.2,
        fatPer100g: 8.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['hydrabadi biryani', 'hyderabadi biryani', 'biryani'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15139',
        name: 'Chick Peas Curry',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 126,
        carbsPer100g: 10.3,
        proteinPer100g: 6.0,
        fatPer100g: 5.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['chick peas curry', 'chickpea curry', 'chana curry'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15140',
        name: 'Bhature (Fried Indian Bread)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 337,
        carbsPer100g: 35.9,
        proteinPer100g: 5.9,
        fatPer100g: 18.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['bhature', 'fried indian bread', 'bhatura'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15141',
        name: 'Pumpkins with Peanut Butter',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 86,
        carbsPer100g: 5.4,
        proteinPer100g: 2.6,
        fatPer100g: 5.5,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['pumpkins with peanut butter', 'pumpkin with peanut butter', 'malenge na peanut butter'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15142',
        name: 'Firinda (Skinned Bean Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 93,
        carbsPer100g: 10.2,
        proteinPer100g: 5.2,
        fatPer100g: 2.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['firinda', 'skinned bean stew', 'bean stew skinned'],
    ),
  ];
}
