import 'food_search_models.dart';

class KenyanFoodCatalogEntry {
  final FoodSearchResult result;
  final List<String> aliases;

  const KenyanFoodCatalogEntry({
    required this.result,
    required this.aliases,
  });
}

class KenyanFoodCatalog {
  KenyanFoodCatalog._();

  static final List<KenyanFoodCatalogEntry> entries = [
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15053',
        name: 'Githeri (Stewed Maize & Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 157,
        carbsPer100g: 19.7,
        proteinPer100g: 6.7,
        fatPer100g: 4.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri', 'stewed maize and beans', 'maize and beans', 'maharagwe na mahindi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15055',
        name: 'Githeri (Sauteed Fresh Maize & Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 185,
        carbsPer100g: 17.8,
        proteinPer100g: 6.9,
        fatPer100g: 7.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri fresh maize', 'sauteed fresh maize and beans', 'fresh maize and beans'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15060',
        name: 'Githeri (Fresh Beans & Maize)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 180,
        carbsPer100g: 15.1,
        proteinPer100g: 7.8,
        fatPer100g: 7.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['githeri fresh beans', 'fresh beans and maize', 'green beans and maize'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15054',
        name: 'Mukimo (Maize, Beans, Potatoes & Pumpkin Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 118,
        carbsPer100g: 20.5,
        proteinPer100g: 5.0,
        fatPer100g: 0.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo', 'irio', 'maize beans potatoes pumpkin leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15057',
        name: 'Mukimo (Fresh Maize, Potatoes & Pumpkin Leaves)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 109,
        carbsPer100g: 18.5,
        proteinPer100g: 3.0,
        fatPer100g: 1.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo fresh maize', 'irio fresh maize', 'fresh maize potatoes pumpkin leaves'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15059',
        name: 'Mukimo wa Njahi (Black Beans, Green Bananas & Potatoes)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 164,
        carbsPer100g: 26.5,
        proteinPer100g: 9.5,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo wa njahi', 'njahi mukimo', 'black beans green bananas potatoes'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15062',
        name: 'Mukimo wa Njahi (Raw & Ripe Bananas)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 151,
        carbsPer100g: 26.6,
        proteinPer100g: 6.4,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['mukimo wa njahi bananas', 'njahi bananas', 'raw ripe bananas njahi'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15056',
        name: 'Matoke (Stewed Green Bananas & Meat)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 118,
        carbsPer100g: 13.3,
        proteinPer100g: 6.0,
        fatPer100g: 4.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['matoke', 'matooke', 'stewed green bananas and meat', 'green banana stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15086',
        name: 'Muthokoi (Dehulled Maize and Beans)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 161,
        carbsPer100g: 19.8,
        proteinPer100g: 5.0,
        fatPer100g: 5.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['muthokoi', 'dehulled maize and beans', 'shelled maize and beans'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15017',
        name: 'Omena Stew (Silver Sardine Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 180,
        carbsPer100g: 6.0,
        proteinPer100g: 8.8,
        fatPer100g: 13.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['omena', 'omena stew', 'silver sardine stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15087',
        name: 'Beef Stew',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 181,
        carbsPer100g: 3.8,
        proteinPer100g: 17.7,
        fatPer100g: 10.4,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['beef stew', 'nyama stew', 'mchuzi wa nyama'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15066-rice',
        name: 'Biryani Rice',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 152,
        carbsPer100g: 27.9,
        proteinPer100g: 2.7,
        fatPer100g: 3.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['biryani rice', 'wali wa biryani'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15066-stew',
        name: 'Biryani Stew (Swahili Spiced Beef Stew)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 198,
        carbsPer100g: 8.3,
        proteinPer100g: 8.1,
        fatPer100g: 14.3,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['biryani stew', 'swahili spiced beef stew'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15074',
        name: 'Wali wa Kuchemshwa (Boiled Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 138,
        carbsPer100g: 27.2,
        proteinPer100g: 2.7,
        fatPer100g: 2.0,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wali wa kuchemshwa', 'boiled rice', 'plain rice'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15075',
        name: 'Wali wa Yasmin (Onion Fried Rice)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 185,
        carbsPer100g: 31.2,
        proteinPer100g: 3.2,
        fatPer100g: 5.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['wali wa yasmin', 'onion fried rice'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15081',
        name: 'Chai ya Maziwa (Mixed Tea)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 36,
        carbsPer100g: 5.4,
        proteinPer100g: 1.1,
        fatPer100g: 1.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_mixed_dishes',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['chai ya maziwa', 'milk tea', 'kenyan tea', 'chai'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15005',
        name: 'Whole Maize Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 141,
        carbsPer100g: 26.0,
        proteinPer100g: 3.3,
        fatPer100g: 1.8,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['ugali', 'maize ugali', 'whole maize ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15009',
        name: 'Refined Maize Flour Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 148,
        carbsPer100g: 27.3,
        proteinPer100g: 3.4,
        fatPer100g: 1.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['refined maize ugali', 'sifted ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15100',
        name: 'Finger Millet Ugali',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 120,
        carbsPer100g: 21.0,
        proteinPer100g: 2.9,
        fatPer100g: 0.7,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['finger millet ugali', 'wimbi ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15051',
        name: 'Ugali (Cassava, Fingermillet and Sorghum Flour)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 145,
        carbsPer100g: 30.7,
        proteinPer100g: 2.0,
        fatPer100g: 0.6,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['cassava finger millet sorghum ugali', 'mixed flour ugali'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15019',
        name: 'White Chapati',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 424,
        carbsPer100g: 49.6,
        proteinPer100g: 7.8,
        fatPer100g: 21.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['chapati', 'white chapati', 'chapo'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15020',
        name: 'Brown Chapati',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 413,
        carbsPer100g: 40.9,
        proteinPer100g: 7.3,
        fatPer100g: 22.9,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_staples',
        servingOptions: [FoodServingOption(label: '100 g', quantity: 100, unit: 'g')],
        matchScore: 0,
      ),
      aliases: ['brown chapati', 'whole wheat chapati'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15001',
        name: 'Uji wa Mahindi (Maize Porridge)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 52,
        carbsPer100g: 8.5,
        proteinPer100g: 1.5,
        fatPer100g: 1.1,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji', 'uji wa mahindi', 'maize porridge', 'porridge'],
    ),
    KenyanFoodCatalogEntry(
      result: FoodSearchResult(
        id: 'kfct-15014',
        name: 'Finger Millet Porridge (Uji wa Wimbi)',
        subtitle: 'Kenya Food Composition Tables 2018',
        caloriesPer100g: 40,
        carbsPer100g: 7.8,
        proteinPer100g: 0.7,
        fatPer100g: 0.2,
        defaultQuantity: 100,
        quantityUnit: 'g',
        source: 'Kenya FCT 2018',
        groupKey: 'kenyan_breakfast',
        servingOptions: [FoodServingOption(label: '100 ml', quantity: 100, unit: 'ml')],
        matchScore: 0,
      ),
      aliases: ['uji wa wimbi', 'finger millet porridge', 'wimbi porridge'],
    ),
  ];
}
