// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjyPz1HncRBSimRsBUUU-xzlUGT_xE9yc',
    appId: '1:312721415465:web:b8e5c83b9f214f406a2b38',
    messagingSenderId: '312721415465',
    projectId: 'nutriwise-001',
    authDomain: 'nutriwise-001.firebaseapp.com',
    storageBucket: 'nutriwise-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowTqCrlmng71MyGqLA34qUCtdzo-JKt0',
    appId: '1:312721415465:android:9e16311da42f609a6a2b38',
    messagingSenderId: '312721415465',
    projectId: 'nutriwise-001',
    storageBucket: 'nutriwise-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVBntblN5H4Mj1NdH5YSmAj5WY3wIplI',
    appId: '1:312721415465:ios:dbd9c6450335892e6a2b38',
    messagingSenderId: '312721415465',
    projectId: 'nutriwise-001',
    storageBucket: 'nutriwise-001.firebasestorage.app',
    iosBundleId: 'com.example.nutriwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQVBntblN5H4Mj1NdH5YSmAj5WY3wIplI',
    appId: '1:312721415465:ios:dbd9c6450335892e6a2b38',
    messagingSenderId: '312721415465',
    projectId: 'nutriwise-001',
    storageBucket: 'nutriwise-001.firebasestorage.app',
    iosBundleId: 'com.example.nutriwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjyPz1HncRBSimRsBUUU-xzlUGT_xE9yc',
    appId: '1:312721415465:web:d63754a4ec60c79a6a2b38',
    messagingSenderId: '312721415465',
    projectId: 'nutriwise-001',
    authDomain: 'nutriwise-001.firebaseapp.com',
    storageBucket: 'nutriwise-001.firebasestorage.app',
  );
}
